apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-app-deployment
  labels:
    app: jenkins-app
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: jenkins-app
  template:
    metadata:
      labels:
        app: jenkins-app
    spec:
      containers:
      - name: jenkins-app
        image: AyaAdel11/jenkins-app:1.0.7
        ports:
        - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-app-service
spec:
  selector:
    app: jenkins-app
  ports:
    - protocol: TCP
      port: 80 # البورت اللي هتدخلي بيه من بره
      targetPort: 8080 # البورت اللي جوه الكونتينر
  type: NodePort # بيسمح لك تدخلي للتطبيق عن طريق IP الجهاز وبورت عشوائي
